server:
  port: 9988

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://172.31.19.154:3306/lease
      username: root
      password: JX@010208
  data:
    redis:
      host: 172.31.19.154
      port: 6379
      database: 0
      password: JX@010208
  jackson:
    time-zone: GMT+8

mybatis-plus:
  configuration:
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

minio:
  endpoint: http://172.31.19.154:9000
  access-key: JXX
  secret-key: JX@010208
  bucket-name: lease

springdoc:
  default-flat-param-object: true

jwt:
  expiration: 3600s
  sign-key: psoEkv6hx5Sc72L00iIBSxlYZSteHyg3